name: Go Compression Benchmark

on:
  push:
    branches: [ main ] # mainブランチへのpushで実行 (必要に応じて変更)
  pull_request:
    branches: [ main ] # mainブランチへのpull requestでも実行 (必要に応じて変更)
  workflow_dispatch: # 手動実行も可能にする

jobs:
  benchmark:
    runs-on: ubuntu-latest # 実行環境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # プロジェクトで使用するGoのバージョン

    - name: Install dependencies
      run: |
        go mod download
        go install github.com/tsenart/vegeta/v12@latest

    - name: Run Go Benchmarks
      run: go test -bench=. -benchmem ./internal/compressor > go_benchmark_results.txt
      # 結果をファイルに出力

    - name: Build server
      run: go build -o server_app ./cmd/server

    - name: Start server in background
      run: ./server_app & # バックグラウンドでサーバーを起動
      # GitHub Actions環境では、バックグラウンドプロセスが後続ステップで利用可能

    - name: Wait for server to start
      run: |
        echo "Waiting for server to start..."
    - name: Run Load Tests
      run: go test -v -run ^TestLoad$ -timeout 0 ./internal/handler/...
      # -v: 詳細出力
      # -run ^TestLoad$: TestLoad関数のみ実行
      # -timeout 0: タイムアウト無制限
      # ./internal/handler/...: テスト対象パッケージ

        timeout=60 # 最大待機時間 (秒)
        start_time=$(date +%s)
        while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ | grep -q 200; do
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge $timeout ]; then
            echo "ERROR: Server did not start within ${timeout} seconds."
            exit 1
          fi
          sleep 2
        done
        echo "Server started!"


    - name: Upload Go Benchmark Results
      uses: actions/upload-artifact@v4
      with:
        name: go-benchmark-results
        path: go_benchmark_results.txt

    - name: Upload Load Test Results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-results
        path: results/ # results ディレクトリ全体をアップロード